---
# Configuration for Web Servers
apache_package: apache2
apache_service: apache2
apache_config_file: /etc/apache2/apache2.conf
document_root: /var/www/html

# Apache modules to enable
apache_modules:
  - rewrite
  - ssl

# Virtual hosts
apache_vhosts:
  - name: default
    port: 80
    document_root: "{{ document_root }}"

# Web server ports
web_server_port: 80
ssl_port: 443 